import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"
